### ISSUE TITLE
Add package build

### ISSUE THREAD

**Issue by gromdimon** [bihealth/autopvs1#10]
**Is your feature request related to a problem? Please describe.**
Currently we don't have package build (setup.py). However, it'll be useful for future.

**Describe the solution you'd like**
Set up package.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Actually that is deprecated. I'd go with Setuptools and pyproject.toml

https://packaging.python.org/en/latest/tutorials/packaging-projects/
