### ISSUE TITLE
Enhance main script

### ISSUE THREAD

**Issue by gromdimon** [bihealth/autopvs1#9]
**Is your feature request related to a problem? Please describe.**
We use main.py to execute the CLI, however, for this purpose there's __main__.py file.

**Describe the solution you'd like**
We should migrate to __main__.py

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
You can also use the Typer library and set an entry point in pyproject.toml. Then, `pip install -e .`
